### ISSUE TITLE
Can I get a free IP certificate?

### ISSUE THREAD

**Issue by DavidDengHui** [HiCA-ACME/docs#12]
It's March 2023, can I get a free IP domain certificate with ACME.SH tool now? 

Use the following command on the terminal: 

`acme.sh --issue -d X.X.X.X --webroot /www/wwwroot/default --days 150 --keylength 2048 --server https://acme.hi.cn/directory`

Tip: I have to pay ¥210.

**Comment by DavidDengHui** [comment]
如题，使用上述命令需要支付200元才能继续，现在还能免费使用吗？

**Comment by xiaohuilam** [comment]
According to high cost due to abuse, the IP address certificates aren't no longer free since 1st Feb.
Sorry for the inconvenience we caused.
